### ISSUE TITLE
PCSE00693 DLC's doesn't work.

### ISSUE THREAD

**Issue by ShinRaikdou** [dots-tb/rePatch-reDux0#10]
As titles says PCSE00693 DLC's doesn't work.
Tried:
nonpdrm dlc in /addcont/ - crashes on startup. C2-12828-1 error.
Decrypted and encrypted in /reAddcont/ - game can't find them.

Reason to use rePatch is uncensored patch inside /rePatch/
This is not my first use of that plugin, all other games works fine in both reAddcont rePatch folders.

PSVita fat 3.65 enso with default sony mc
Config (already tried to disable all plugins expect repatch and nonpdrm):
```
*KERNEL
ux0:tai/nonpdrm.skprx
ux0:tai/repatch.skprx
ux0:tai/noled.skprx

*main
ux0:tai/shellbat.suprx

*ALL
ux0:tai/oclockvita.suprx
```

upd: tried to use https://github.com/SilicaAndPina/rePatch/releases and it's working as it should. This is definitely problem in reDux0 build (that I like more because of decrypted addcont feature).

**Comment by dots-tb** [comment]
Have you run rePatch AIDS?

**Comment by ShinRaikdou** [comment]
> Have you ran rePatch AIDS? (with the decrypted in reAddcont and encrypted in addcont)

Yes. Game didn't see dlc and can't load saves with them.

**Comment by dots-tb** [comment]
Does rePatch AIDS generate folders for the corresponding decrypted dlc in encrypted addcont? Do you have the most up to date vitashell?

**Comment by ShinRaikdou** [comment]
> Does rePatch AIDS generate folders for the corresponding decrypted dlc in encrypted addcont? Do you have the most up to date vitashell?
No, all other dlc's installing fine with generating folders except that damn PCSE00693. Yes, my vitashell is 1.94.
Tried to delete game and refresh it without encrypted dlc - still no luck with AIDS and putting both encrypted or decrypted into reAddcont.

Btw, I resolved issue with PCSE00398 by reinstalling aids.

**Comment by dots-tb** [comment]
Oh alright, good to hear :)

**Comment by ShinRaikdou** [comment]
>Oh alright, good to hear :)

You get it wrong :) I resolve minor issue with PCSE00398, but PCSE00693 all the same.

**Comment by ShinRaikdou** [comment]
> Oh, alright... Can you try vitashell 1.9, then run AIDS?

Nothing changed.

**Comment by ShinRaikdou** [comment]
Didn't work.

**Comment by dots-tb** [comment]
Like the game still doesnt work or AIDs doesnt work?

**Comment by ShinRaikdou** [comment]
I mean folder is not created and dlc doesn't work.

**Comment by dots-tb** [comment]
Does PCSE00693 exist in ur0:appmeta? Does AIDs complete its run?

**Comment by ShinRaikdou** [comment]
Yes and yes.

**Comment by dots-tb** [comment]
Alright, I will look into it soon, sorry for all the questions.

**Comment by Mesomeso** [comment]
Just wanted to report that I got the same problem, but with a PSVITA 1000 3.68 with h-encore. Using the DLCs makes a C2-12828-1 error.

**Comment by guicogo** [comment]
Same here with Enso 3.65.

**Comment by nkrapivin** [comment]
Same, but with Minecraft PSVita PCSB00560, I have downloaded all encrypted DLCs from NPS and tried to fake another 2, well, funny, encrypted texture packs working, skinpacks do not. ;(

**Comment by dots-tb** [comment]
@Mesomeso @guicogo To confirm, you mean that you are playing the same game, correct?
@nkrapivin I don't know if fake dlc counts towards this issue since the game may require external assets and this issue is specific to PCSE00693.

**Comment by Mesomeso** [comment]
@dots-tb Yes, PCSE00693 (Dungeon Travelers 2 (USA)) and for the same thing (uncensored patch).
Basically:
PCSE00693 + DLC = works 
PCSE00693 + Uncensored patch = works
PCSE00693 + DLC + Uncensored patch = C2-12828-1 error
Also tried using AIDs, but still the same. (Everything with the latest build).

**Comment by guicogo** [comment]
@dots-tb Yes, PCSE00693 is the problematic game. Unlike @Mesomeso, I have different results:
PCSE00693 = works
PCSE00693 + DLC = C2-12828-1 error
PCSE00693 + Uncensored patch = works
PCSE00693 + DLC + Uncensored patch = C2-12828-1 error
AIDS didn't help. Everything except the Uncensored patch was downloaded from PKGJ, even tried NPS Browser, had same result.

**Comment by dots-tb** [comment]
I had testers say that PCSE00693 +any NoNpDrm DLC does not work, but sadly I can't fix this error until we have all the LetMaiDie stuff has been rolled out. We will try to fix it as soon as possible though. ;-;

**Comment by guicogo** [comment]
@dots-tb No problem, thanks for your time. ^__^

**Comment by Yoti** [comment]
Same error for me. PCH-2006@3.68.

**Comment by Yoti** [comment]
Dump for investigation
[psp2core-1535403146-0x0000052d89-eboot.bin.psp2dmp.zip](https://github.com/dots-tb/rePatch-reDux0/files/2325588/psp2core-1535403146-0x0000052d89-eboot.bin.psp2dmp.zip)

**Comment by Quenser** [comment]
Hello, I'm experiencing the same issue. Only works without DLC or with rePatch disabled.
