### ISSUE TITLE
Games getting stuck after sleep mode/going to home screen

### ISSUE THREAD

**Issue by Ranomez** [dots-tb/rePatch-reDux0#12]
So I am on 3.68 using h-encore and games using rePatch will get stuck shortly after resuming the game if I put the console in sleep mode or go back to the home screen and then back into the game. 
Games I use rePatch with are:
Digimon World Next Order (PCSH00261)-translation, after I go to the home screen/sleep mode the game will just get stuck on a black screen with music still playing correctly when I go to a different map (if it matters 2 cpk files are being replaced using rePatch).
Genkai Tokki Moe Chronicle (PCSH00148)-uncensor patch, similar behavior, if I am in the town I can go back into the shop but the sprite of the shopkeeper will be missing, if I try to go into a dungeon it gets stuck on a black screen with the music playing (1 cpk file is being replaced for this one).

**Comment by dots-tb** [comment]
#7
