### ISSUE TITLE
Possibility of rePatch loading files from a different mount point than ux0?

### ISSUE THREAD

**Issue by Ranomez** [dots-tb/rePatch-reDux0#13]
Since I am using a SD2Vita that gets mounted as ux0 and the Vita memory card which gets mounted as uma0 has very low usability, I am only aware of Adrenaline being able to use it and I do not personally have any use for PSP/PS1 games on the Vita so I was wondering if it would be possible to make rePatch able to load the patched files from different mount points also and not just from ux0?
I think this would also help people that use a PSTV with USB storage and a Vita memory card, Vita owners that have both a PSVSD and a SD2Vita, etc. 
Since the files patched by rePatch can then be deleted from the original game folders it could even allow installing more games on ux0 for people that have a different storage option as well, I personally have a game for which the patched files are around 1.4GB and my Vita came with an 8GB card.

**Comment by dots-tb** [comment]
Yes, this is an idea I've had. It's on the roadmap.
