### ISSUE TITLE
Fully Decrypted eboots (with FAGDec) are "disabling" rePatch with NoNpDrm games

### ISSUE THREAD

**Issue by DeathChaos25** [dots-tb/rePatch-reDux0#16]
Basically, when you Decrypt an eboot with FAGDec, this decrypted eboot makes rePatch completely stop working, neither update replacements (replacing files in patch directory) nor DLC mods are working with a decrypted eboot (untouched) or modified (rebuilt after being decrypted),  removing the decrypted eboot makes all files work again.

This essentially makes eboot mods impossible to use with NoNpDrm games.

(Tested with both PCSG01030 and PCSG01031)

(This might not be specific with NoNpDrm but those are the only games I have immediately available that have had both updates and DLCs that I have patched).

**Comment by dots-tb** [comment]
Are you putting the self_auth.bin into the rePatch folder?

**Comment by DeathChaos25** [comment]
The modified and untouched eboots work, the game files being replaced by rePatch (or DLCs) are the ones that stop working with the new eboot.

Tried the self_auth.bin from the base game's eboot, and one from the latest game update (this is the eboot we're trying to patch/modify), put the self_auth.bin from both eboots in the same directory where the new eboot is being placed, the modified eboot is working (already was), but the rest of the rePatch features still don't work with either of the self_auth.bin files.

**Comment by dots-tb** [comment]
Are you using make_fself and changing the auth_id? This is the latest pre-release repatch right?

**Comment by DeathChaos25** [comment]
Yes to both questions, eboot was repacked using the instructions from here;
https://github.com/CelesteBlue-dev/PSVita-RE-tools

That being said, even if you only decrypt the eboot using FAGDec, and the eboot is 100% untouched aside from being decrypted, this still disables patch/dlc modding on rePatch.

**Comment by dots-tb** [comment]
Alright, let me know the results.

**Comment by CelesteBlue-dev** [comment]
lmao
