### ISSUE TITLE
pcse00974 - error C2-12828-1 on 3.60 enso

### ISSUE THREAD

**Issue by omikron24** [dots-tb/rePatch-reDux0#18]
Steps to reproduce on 3.60:
Title requires 3.61

1. Installed repatch_4.skprx in ux0:tai/  (latest version 2.71 from 24th july )
2. Added repatch_4.skprx under kernel in config.txt
3. created "rePatch" folder in ux0:
4. Reboot
5. PKGJ - added comppacks url to config.txt in ux0:/pkgi/
6. PKGJ - downloaded PCSE00974 (will refer to this as "title")
7. PKGJ - downloaded comppack for the title.
8. Before proceeding checked if the title folder is in ux0:tai/ - confirmed
9. Before proceeding checked if the title folder is in ux0:/rePatch/ - confirmed
10. Refreshed livearea from vitashell 1.94
11. Lauched title from live area - C2-12812-1 Error.

Tried a different approach

12. Checked the ux0:tai/patch - no title folder
13. Manually created the folder and added encrypted title files
14. Launched title form live area - error "tittle corrupted"
15. Deleted title folder from ux0:/patch
16. Lauched title from live area - C2-12812-1 Error.

Tried getting the title from another source (NPS browser)

Repeated steps 1-11, same result.

Same thing happens if I install repatch in ur0:tai/ with corresponding config.

**Comment by dots-tb** [comment]
Why is there a rePatch folder in ux0:tai? The only interaction you should have with the tai folder is editing the config.txt and installing repatch. Can you please show me your config?

**Comment by omikron24** [comment]
Typo, it is in ux0:

**Comment by dots-tb** [comment]
Can you show me the config.txt?

**Comment by SuicidePigGod** [comment]
Hey i have the exact same error these are the steps i did
Steps to reproduce on 3.60:
Title requires 3.67

1. Installed repatch_4.skprx in ur0:tai/ (latest version 2.71)
2. Added repatch_4.skprx under kernel in config.txt
3. created "rePatch" folder in ux0:
4. Reboot
5. PKGJ - added comppacks url to config.txt in ux0:/pkgi/
6. PKGJ - downloaded PCSEG01030 
7. PKGJ - downloaded comppack for PCSEG01030
8. Before proceeding checked if the title folder is in ux0:/app - confirmed
9. Before proceeding checked if the title folder is in ux0:/rePatch/ - confirmed
10. Refreshed livearea from vitashell 1.94
11. Lauched title from live area - Getting the error that i need to update my system to play this title

**Comment by itsminht** [comment]
Check version spoofing in henkaku settings is enabled and set to fw 3.61 or higher

**Comment by omikron24** [comment]
Quick update. Spoofing was set to 3.67 by default. When manually changed to 3.68 - game starts.

**Comment by FreddyBoubil** [comment]
Hi,

I have the same issue, 3.60 Enso. I give here my info if it can help.

All the games have been downloaded with NPS Browser 0.93, the ComPatch too (I always took the last one). The files are then uploaded on the Vita with FTP, ux0:/app for games, ux0:/rePatch for ComPatch. Each game has its folder with its id, the same for ComPatch. LiveArea refreshed with Vita Browser 1.92

On the Vita I tried rePatch reDux0 2.61 + 0.09 and rePatch reDux0 2.71 (ALPHA). The .skprx file is in ur0:/tai and added under "Kernel" in ur0:/tai/config.txt

Spoof version is enabled in Henkaku settings, set to 3.68

Here are the games which run ok : 
Sir Eatsalot PCSG01170 : works on 2.71 but error c2-12828-1 on 2.61
Rogue Aces PCSE01198 : works on both
Liar Princess And The Blind Prince PCSG01191 : works on both

Here are the games which give error c2-12828-1 : 
Chasm PCSE01031
Darkest Dungeon PCSE00919
Super Destronaut DX PCSB01251

**Comment by itsminht** [comment]
strange, the games you mention that aren't working is working perfectly fine for me here. I have 3.65 ENSO not sure if that makes a difference.

**Comment by FreddyBoubil** [comment]
Maybe you could upload one of the games with its compatch so that I can try your version, in case I did something wrong.

**Comment by FreddyBoubil** [comment]
Hi,

I solved my problem by installing the last patch for each game. 

In NPS Browser, right click on the game, "check for patches", download. Then transfer the folder with its files in ux0:/patch.
