### ISSUE TITLE
installed then got a bootloop

### ISSUE THREAD

**Issue by Flyingsquids** [dots-tb/rePatch-reDux0#19]
Installed the VPK then rebooted my system to find its bricked. Stuck on the Molecular boot screen. 
Running 3.60 enso

**Comment by Flyingsquids** [comment]
figured out it was repatch_4.skprx 
I have it in the ux0:tai/ folder and configured in the ur0:tai/config.txt as [ux0:tai/repatch_4.skprx]. I plugged the sd into my pc and removed the repatch_4 from the ux0:tai folder and I booted right up.

**Comment by Flyingsquids** [comment]
Check Check. redid it all with repatch in the ur0 folder and configged accordingly and it still behaves the same.

**Comment by dots-tb** [comment]
You can disable plugins on boot up by holding L. Please use the thread #15 and make sure that you do not have any conflicting plugins.

**Comment by SilicaAndPina** [comment]
Should @skgleba

**Comment by Flyingsquids** [comment]
did that, got back into molecularshell. Now I have to reconfig my config because it got reset and when the vita turns on now its like a new vita, all my stuff is gone from the home screen.

**Comment by Flyingsquids** [comment]
Seems i got it fixed. Just have to reconfig, rebooted and it updated database and all my stuff is back and running. Could of gone the night without that heartattack

**Comment by Flyingsquids** [comment]
Only problem being why it happened in the first place. I'd rather not go through all that again. It seemed to go screwy when I put repatch into the Tai config.

**Comment by dots-tb** [comment]
The problem is that there is a timing issue between henkaku's startup and repatch. If it is slowed down or sped up too fast then it causes an issue.
