### ISSUE TITLE
PCSG01030 - need to update error Enso 3.60

### ISSUE THREAD

**Issue by SuicidePigGod** [dots-tb/rePatch-reDux0#20]
Hey so i have this error these are the steps i did:
Steps to reproduce on 3.60:
Title requires 3.67
I,m using sd2vita btw

1. Installed repatch_4.skprx in ur0:tai/ (latest version 2.71)
2. Added repatch_4.skprx under kernel in config.txt
3. created "rePatch" folder in ux0:
4. Reboot
5. PKGJ - added comppacks url to config.txt in ux0:/pkgi/
6. PKGJ - downloaded PCSEG01030 
7. PKGJ - downloaded comppack for PCSEG01030
8. Before proceeding checked if the title folder is in ux0:/app - confirmed
9. Before proceeding checked if the title folder is in ux0:/rePatch/ - confirmed
10. Refreshed livearea from vitashell 1.94
11. Lauched title from live area - Getting the error that i need to update my system to play this title

This is my config.txt

#Kernel
ur0:tai/gamesd.skprx
ur0:tai/repatch_4.skprx
ur0:tai/nonpdrm.skprx

**Comment by wbc8615728** [comment]
you can test update this game by psvself-gameupdate




On 07/27/2018 19:33, SuicidePigGod wrote:

Hey so i have this error these are the steps i did:
Steps to reproduce on 3.60:
Title requires 3.67

Installed repatch_4.skprx in ur0:tai/ (latest version 2.71)
Added repatch_4.skprx under kernel in config.txt
created "rePatch" folder in ux0:
Reboot
PKGJ - added comppacks url to config.txt in ux0:/pkgi/
PKGJ - downloaded PCSEG01030
PKGJ - downloaded comppack for PCSEG01030
Before proceeding checked if the title folder is in ux0:/app - confirmed
Before proceeding checked if the title folder is in ux0:/rePatch/ - confirmed
Refreshed livearea from vitashell 1.94
Lauched title from live area - Getting the error that i need to update my system to play this title

**Comment by SuicidePigGod** [comment]
updating didnt fix this

**Comment by dots-tb** [comment]
Do you have system firmware spoofing to the latest enabled in henkaku?

**Comment by SuicidePigGod** [comment]
oh my god the issue is now fixed thank you very much
