### ISSUE TITLE
Compilation fails for PS4 targets

### ISSUE THREAD

**Issue by nyaasen** [dots-tb/rePatch-reDux0#22]
pls 2 halp

**Comment by dots-tb** [comment]
https://github.com/dots-tb/rePatch-reDux0/wiki/Debug-Info-for-Bugs-and-Modding
Can you please install ShipLog,
Create the folder ux0:dump, 
Start the application with the DLC installed that causes the crash, 
Then go into ShipLog's application and DUMP LOG BUFFER TO DISK,
Please upload that logger.txt.

Thanks.
