### ISSUE TITLE
Crash on PCSE00568

### ISSUE THREAD

**Issue by holictsubasa** [dots-tb/rePatch-reDux0#24]
When I tried to start this game and it crash, I have DLC downloaded from pkgj, if I delete it, the game works, but if I tried to run the game with the DLC it crashes, even if I don't have the PCSE00568 in rePatch folder nor reAddcont folder. If I delete the repatch plugin, the game works with the DLC. Sorry for my bad english.

**Comment by dots-tb** [comment]
https://github.com/dots-tb/rePatch-reDux0/wiki/Debug-Info-for-Bugs-and-Modding
Can you please install ShipLog,
Create the folder ux0:dump, 
Start the application with the DLC installed that causes the crash, 
Then go into ShipLog's application and DUMP LOG BUFFER TO DISK,
Please upload that logger.txt.

Thanks.

**Comment by the-importer** [comment]
@dots-tb 
You're gonna have your hands full with log files for the weekend

**Comment by holictsubasa** [comment]
[VitaShellPatch             ]:Starting...  OK        350usec
3:0x9cd098e26c7c132a:0x8c2ff5fd:[coredump] start ID=PCSE00568
3:0x9cd098e2e133745a:0x8c2ff5fd:[coredump] done
this is a test

**Comment by dots-tb** [comment]
@holictsubasa Sorry, I forgot to mention the debug build of rePatch. Did you happen to install it ?

**Comment by holictsubasa** [comment]
oh, sorry, this is the file logger.txt with that build:

ShipLog
Net logging: 0
File logging: 0
hooks:
hooks[SceNetPsForDriver_1ABF937D]: 0
hooks[sceKernelGetStdout]: 11c2f
Setting debug handler: 1aa0045
Setting putchar handler: 1aa00e9
[backdoor_exe               ]:Starting...  OK     146906usec
[taihen                     ]:Starting...  OK   10384558usec
[HENkaku                    ]:Starting...  OK       4009usec

PSP2 Kernel Booting Time : -54423 [msec]

[Shell]: vsh/release_branches/release_03.650 r142704 (build#757166)

*** network ready. myaddr: 192.168.1.74 ***
newPath ux0:/rePatch/NPXS10079/eboot.bin
newPath ux0:/rePatch/NPXS10079/sce_sys/param.sfo
vshbridge : shell ready
newPath ux0:/rePatch/NPXS10063/eboot.bin
newPath ux0:/rePatch/NPXS10063/sce_sys/param.sfo
newPath ux0:/rePatch/NPXS10063/sce_sys/nptitle.dat
newPath ux0:/rePatch/PCSE00568/eboot.bin
newPath ux0:/rePatch/PCSE00568/sce_sys/param.sfo
newPath ux0:/rePatch/PCSE00568/sce_sys/keystone
newPath ux0:/rePatch/PCSE00568/sce_module/libfios2.suprx
newPath ux0:/rePatch/PCSE00568/sce_module/libfios2.suprx
newPath ux0:/rePatch/PCSE00568/sce_module/libc.suprx
newPath ux0:/rePatch/PCSE00568/sce_module/libc.suprx
newPath ux0:/rePatch/PCSE00568/Data/NowLoading/NowLoading001.pck
newPath ux0:/rePatch/PCSE00568/Data/Init/general.tex
newPath ux0:/rePatch/PCSE00568/Data/Init/advframe.tex
newPath ux0:/rePatch/PCSE00568/Data/Init/advframe.bin
newPath ux0:/rePatch/PCSE00568/Data/Init/cursor1.pck
newPath ux0:/rePatch/PCSE00568/Data/Init/cursor2.pck
newPath ux0:/rePatch/PCSE00568/Data/Init/advSkip.pck
newPath ux0:/rePatch/PCSE00568/Data/Init/item_iconA.tex
newPath ux0:/rePatch/PCSE00568/Data/Init/item_iconA.tex
newPath ux0:/rePatch/PCSE00568/Data/Init/item_iconB.tex
newPath ux0:/rePatch/PCSE00568/Data/Init/item_iconB.tex
newPath ux0:/rePatch/PCSE00568/Data/Init/item_iconC.tex
newPath ux0:/rePatch/PCSE00568/Data/Init/item_iconC.tex
newPath ux0:/rePatch/PCSE00568/Data/Init/item_iconD.tex
newPath ux0:/rePatch/PCSE00568/Data/Init/item_iconD.tex
newPath ux0:/rePatch/PCSE00568/Data/Init/item_iconE.tex
newPath ux0:/rePatch/PCSE00568/Data/Init/item_iconE.tex
newPath ux0:/rePatch/PCSE00568/Data/Init/item_iconF.tex
newPath ux0:/rePatch/PCSE00568/Data/Init/item_iconG.tex
newPath ux0:/rePatch/PCSE00568/Data/Init/item_iconH.tex
newPath ux0:/rePatch/PCSE00568/Data/Init/item_iconI.tex
newPath ux0:/rePatch/PCSE00568/Data/Init/item_iconJ.tex
newPath ux0:/rePatch/PCSE00568/Script/Script.pck
newPath ux0:/rePatch/PCSE00568/Font.pck
newPath ux0:/rePatch/PCSE00568/FontMes.pck
newPath ux0:/rePatch/PCSE00568/Exi_NOR.pck
newPath ux0:/rePatch/PCSE00568/Venv.pck
newPath ux0:/reAddcont/PCSE00568/NORDLCONTENTS000
newPath ux0:/reAddcont/PCSE00568/NORDLCONTENTS001/sce_sys
newPath ux0:/reAddcont/PCSE00568/NORDLCONTENTS001/sce_sys
3:0x9cd098e26c7c132a:0x8c2ff5fd:[coredump] start ID=PCSE00568
3:0x9cd098e2e133745a:0x8c2ff5fd:[coredump] done
newPath ux0:/rePatch/SHIP00001/eboot.bin
newPath ux0:/rePatch/SHIP00001/sce_sys/param.sfo
newPath ux0:/rePatch/SHIP00001/sce_sys/keystone
this is a test

**Comment by dots-tb** [comment]
@holictsubasa Can you run it with that debug version, without DLC (if it runs) so I can see the normal start up pattern.

**Comment by holictsubasa** [comment]
When I tried to run the game with the debug build, the vita freezes completely, the I have to reboot it with the on/off button, that doesn't happend with the normal build. If I try to DUMP LOG BUFFER TO DISK, the logger.txt file doesn't contains anything about PCSE00568.

**Comment by dots-tb** [comment]
Hmm probably too many logs for it to hold memory, thanks for trying though. If you want to pursue further you can try setting up net, but you dont have to.

**Comment by Dantenerosas** [comment]
@dots-tb, seems like that's the same issue as https://github.com/dots-tb/rePatch-reDux0/issues/17 , tho I can be wrong
