### ISSUE TITLE
Can't load cpk folder placed in repatch

### ISSUE THREAD

**Issue by Testrfr2018** [dots-tb/rePatch-reDux0#27]
I used repatch.skprx ( tag 1.0  ) and it successfully loaded the cpk files in cpk folder in repatch folder , but after I update the plugin tag 2.70 and 2.71 , there was no effect in game any more ,which means the plugin failed to load the cpk . While the decyrpted dlc placed in readdcont folder was successfully loaded. By the way, the cpk file is used to mod the decyrpted game ( nonodprm support ) .
Sorry for my poor English and
Thanks.

**Comment by dots-tb** [comment]
There is no change in how files are loaded between those versions. Also, what game is it?

**Comment by Testrfr2018** [comment]
I wonder is there any possibility of conflict between the plugins? like between  repatch.skprx and repatch_4.skprx?
By the way the game is PCSH10099 Bullet girl phantasia  ( Asia version ).
The patch is used to remove the smoke on character when they take off  the underwear. It's a cpk file in cok folder.

Thanks for the reply.

**Comment by TheRadziu** [comment]
I do use pre-release (2.71) repatch on this game with very same mod and works just fine.

Either its user error or 3.67+ compatibility stuff

**Comment by Testrfr2018** [comment]
Could you please tell me how do you make it works or may you make a easy tutorial ?
My vita is 3.65. and I installed the game using nonodprm plugin. 
I also installed the repatch_4.skprx and repatch.skprx, and the DLC works fine.
But the patch didn't work.
@TheRadziu

**Comment by TheRadziu** [comment]
no wonder it doesnt work if you use multiple versions of same plugin at the same time

**Comment by Testrfr2018** [comment]
But I also tried installing reapatch.skprx alone and still the same……
I have tried different set-up many times already.
@TheRadziu
