### ISSUE TITLE
DLC cannot be loaded in SAO HR [USA]

### ISSUE THREAD

**Issue by ZayedHegazi** [dots-tb/rePatch-reDux0#28]
(Game ID : PCSE00903)

I cannot load my save file if the DLC is installed since it displays a message that says "cannot load the DLC data properly" once I use any version of Repatch that is after Repatch 1.0 . And if I start a new game, the DLC costumes make the character invisible, many have posted about this issue on the subreddit sadly. I have to revert back the first version of Repatch to make the game work :/

**Comment by ZayedHegazi** [comment]
Also , I never modded DLC or anything , I only use the plugin for Persona 4 Undub. The DLC goes to Addcont, so yes I know what I am doing, plus I also install it using PKGJ.

**Comment by dbsuarez** [comment]
I downloaded SAO:HR using NPS Browser and the DLCs using pkgj, all DLCs installed correctly but when I attempt to use Kirito's Movie Costume, the character disappears, after I revert to old armor the character reappear. After a post on reddit, someone suggest that using version 1 of rePatch fixed this problem.. Now if I want to play SAO:HR, i will uncomment the latest version of the plugin in my tai config and enable version 1 or repatch and then reboot, when I want to play a newer game then uncomment version 1 and enable the latest, then reboot..

**Comment by ZayedHegazi** [comment]
I am the one on Reddit who recommended the first version xD
And yes sadly it is annoying since the first version is also flawed  (Persona 4 undub crashes)

**Comment by yurikaka** [comment]
The ASIA version of SAO:HR PCSH00266 has the same problem.
