### ISSUE TITLE
c1-6703-6 error: Can't get Super Robot Taisen X to work.

### ISSUE THREAD

**Issue by AkitoCL** [dots-tb/rePatch-reDux0#30]
**Describe the bug**
Super Robot Taisen X is a 3.67 game which is supposed to work on Enso 3.65 using repatch and a lot of people claim it actually does. But for some reason I just can't get it to work no matter how many times I try dowloading repatch.skprx or I edit the config.txt

**To Reproduce**
I've tried many different ways to get this to work.
1) Download repatch with AutoPlugin in ux0 (obviously I've also used the skprx from here), reboot, copy the Nonpdrm version of the game, refresh live area, update the game through the livearea, copy the comp. pack for 1.04

2) Download repatch_4, edit config.txt, reboot, same as previous step (copy game, refresh, update, copy comp pack)

3) Try copying repatch.skprx to ur0 this time, edit the config.txt found there, and then do the same as previous steps 

4) The same as before, this time with repatch_4 on ur0

5) Have both repatch and repatch_4 on both ux0 and ur0 and edit both of config.txt, rinse and repeat.

6) Do any of the five experiments from before this time without updating the game and using a 1.00 comp pack.

**Additional context**
I've tried downloading the game from this Reddit thread.
https://www.reddit.com/r/VitaPiracy/comments/91wpoa/super_robot_wars_x_asiaenglish_ggoogle_drive_link/?sort=confidence
The comp packs are found in the comments.

**Comment by dots-tb** [comment]
What do you mean it doesn't work? As in it gives an error code or does it just not run?

**Comment by dots-tb** [comment]
What does your rePatch directory look like?

**Comment by AkitoCL** [comment]
https://imgur.com/a/i34U6sQ

**Comment by dots-tb** [comment]
And what does your config look like when you have just repatch_4.skprx on ur0?

**Comment by AkitoCL** [comment]
https://imgur.com/a/eikejkV
Sixth pic is the config.txt, other pictures show different possibly helpful stuff.
My last idea was to think capitalization mattered in the rePatch folder but I ended up getting the same results in the end.

If it helps, I'm using SD2Vita

**Comment by dots-tb** [comment]
You only have repatch_4.skprx in the tai folder and rebooted after making the changes to the config.txt, correct?

**Comment by AkitoCL** [comment]
Yeah, I reboot after each change I do to the tai folder. Have tried with repatch alone, repatch_4 alone and with both at the same time.

**Comment by dots-tb** [comment]
To save time for future testing, you should never have two of the same plugins running. I wonder if there is a conflict with vitacheat.skprx? I don't really know what to say since other people have gotten it to work.

**Comment by AkitoCL** [comment]
I fixed it in the minute I was typing this.
It's the most stupid thing ever.
I tried just to mess around to copy repatch_4 to the tai folder located in uma0 and edit the .txt file there adding the plugin and it worked!
I'm super puzzled about why but I'm also glad.

**Comment by dots-tb** [comment]
Oh... Alright! I'm glad you got it to work :9.
