### ISSUE TITLE
Newest version break pso2 patches

### ISSUE THREAD

**Issue by Greedozx** [dots-tb/rePatch-reDux0#33]
The newest 3.0 version seems to be messing with patches.

I had a 3.60 vita with a fresh install of henkaku/sd2vita/plugins. and i downloaded the game pso2 with its compatibility patch, also installed the english patch released by ARKSlayer

However the game refused to load the english patch and the game suffered from a bug where all the enemies in the game were invisible to me, bug wich can be seen in this recording i did https://www.youtube.com/watch?v=F8DzcSidBpw&feature=youtu.be

Thanks to someone´s suggestion on reddit i tried runing the older. 2.7 version of rePatch and both the game not loading the english patch and the invisible enemies bug vanished. wich means that the issue was with the newest version of rePatch not loading the english patch and messing with the compatibility patch

**Comment by dots-tb** [comment]
Can you screenshot your rePatch folder?

**Comment by dots-tb** [comment]
Does the original base game run on your current firmware? If so could you run FAGDec (linked below) on the APP/BASE (NOT PATCH) of the game, just the eboot to save time (you can use self or elf mode, elf is faster). Then when this is generate, could you copy the resulting ux0:FAGDec/TITLEID/self_auth.bin to your rePatch folder, tell me the results. Thanks in advance.

 https://github.com/CelesteBlue-dev/PSVita-RE-tools/tree/master/FAGDec/build

**Comment by Greedozx** [comment]
hi, unfortunally the original base game does not run in my current firmware (3.60 henkaku spofed to 3.69) if i try to open it without the compatibility pack on the rePatch folder i get error C1-6703-6 . If i try to open it again right after the vita screen fades to black and it reboots itself

**Comment by dots-tb** [comment]
Base game as without the patch? Please just try decrypting ux0:app/titleid/eboot.bin with FAGDec. And if it works, please upload the self_auth.bin here please.

**Comment by Greedozx** [comment]
i allready have a self_auth.bin file on the rePatch folder of the game are you ok with that one or do you need the one of fagdec

**Comment by dots-tb** [comment]
I need the one from the base game/app eboot please.

**Comment by Greedozx** [comment]
it throws me a couple of errors in red letters : [#] Could not properly save self auth: 80010002 and the other one [#] ELD IS CORRUPTED: IT IS AS BAD AS MAI. Or its too

**Comment by Greedozx** [comment]
a few files appeared on the fagdec folder though: ux0:FAGDec/patch/PCSG00141

a eboot.bin and eboot.bin.elf.temp files appeared

**Comment by dots-tb** [comment]
You are doing the app version of the game right, not the patch ver? What did kuEntente return? Do you have a discord?

**Comment by Greedozx** [comment]
[self_auth.zip](https://github.com/dots-tb/rePatch-reDux0/files/2602374/self_auth.zip)

**Comment by dots-tb** [comment]
I'll have to look into this... Y-you sure you don't use discord or anything?

**Comment by Greedozx** [comment]
no sorry :/

**Comment by Greedozx** [comment]
i hope that file helps u fix the app

**Comment by dots-tb** [comment]
I'll get back to you if I can't find any testers :/

**Comment by Aida-Enna** [comment]
> I'll have to look into this... Y-you sure you don't use discord or anything?
> no sorry :/
:eyes:

**Comment by Greedozx** [comment]
IT works know, i installed the 3.0 repatch updated today and now both the english patch and compatibility pac work correctly

**Comment by dots-tb** [comment]
Nice to hear
