### ISSUE TITLE
Steins;Gate 0 doesn't work with modded eboot.bin (3.65)

### ISSUE THREAD

**Issue by Darkmet98** [dots-tb/rePatch-reDux0#4]
Hello, I'm making a mod for Steins:Gate 0 EUR/USA and when I put the decrypted eboot.bin (decrypted on maidump) on rePatch, the game starts and when verifying the thropies, the game crashes with the error C1-2755-9 and the console reboots.

**Comment by dots-tb** [comment]
Maidump eboots are not support ATM, future support will come later! :)

**Comment by Darkmet98** [comment]
Ok, thanks ^^
