### ISSUE TITLE
PCSG00881 Y's VIII JPN - Not working (stuck at splash screen)

### ISSUE THREAD

**Issue by remlei** [dots-tb/rePatch-reDux0#8]
It works on old repatch plugin (silica's version of the plugin).

Game: YS VIII - Lacrimosa of Dana
GAMEID: PCSG0881
NPS Dump: Yes
Region: JPN
rePatch plugin version: v1.00 - v2.61
Notes: applied with patch files for English assets with v1.02 update (all decrypted) placed in ux0:rePatch folder
Note 2: AIDS also crash when scanning the folder PCSG0881 (as I also have some decrypted DLC applied on it).
Issue: Stuck at splash screen.

the only workaround for now is use a the old plugin.

**Comment by dots-tb** [comment]
There is no such thing as a silica version, I wrote every single version of rePatch. Make sure you have an updated vitashell.
Are you using all decrypted dlc or encrypted along side the decrypted?  Where is the DLC atm?
Make sure you follow the modding guide in the wiki and Radziu's guide.
