### ISSUE TITLE
Possibly not working for 3.68?

### ISSUE THREAD

**Issue by the-importer** [dots-tb/rePatch-reDux0#9]
So tried following these instructions to get this working: http://arks-layer.com/nova.php
Tried in ur0 and ux0, nothing worked. If it incompatible with Fat Vitas or am I doing something wrong?

**Comment by dots-tb** [comment]
rePatch was developed on a fat vita. Please check your config.txt, it may be beneficial to post it in full here. Also, please check that you installed the files correctly. If you experience further problems, please contact the developer of that specific translation package.

**Comment by the-importer** [comment]
@dots-tb 
Thank you for your reply. Here are some screenshot of everything I did, tell me if I forgot anything:
https://s8.postimg.cc/jyoy7ozj9/2018-07-05-081322.jpg
https://s8.postimg.cc/jlxk1j4et/2018-07-05-081615.jpg
https://s8.postimg.cc/4pz0txlad/2018-07-05-081718.jpg
https://s8.postimg.cc/dkzv4gpid/2018-07-05-081734.jpg
https://s8.postimg.cc/7wtkdjy0l/2018-07-05-081753.jpg

**Comment by dots-tb** [comment]
You put repatch.suprx instead of repatch.skprx. Please use ur0 only.

**Comment by the-importer** [comment]
@dots-tb 
A simple typo I assure you. This was my 3rd time starting over and wrote *.skprx the other times. I also copied the Tai folder to ux0 and simply changed the config file in order to see if I would get results in ux0 since I had no luck with ur0. In short, still not working. I was positing here to see if I would have forgotten to do anything in order to make this work.

**Comment by dots-tb** [comment]
How did you install the game?

**Comment by the-importer** [comment]
@dots-tb 
Oh I'm sorry, forgot to mention that I'm trying to use it with a physical card. They say on the website that's suppose to work: http://arks-layer.com/nova.php

**Comment by dots-tb** [comment]
And it works, as in starts up, without rePatch installed? You have the latest/correct patch for the game installed recommended for the translation project?

**Comment by the-importer** [comment]
@dots-tb 
Not sure about your question. Are you asking me if the game itself without the translation patch works and if it's up to date? If so, then yes, it runs fine and it's up to date. As for the recommendations to use the translation, they say that you need the last update, 1.05, which I do have. BTW, I did try using a dumped game with the English patch and it does work, but my goal is to use it with  physical card.

**Comment by dots-tb** [comment]
And the title id matches up with cart's title id? Also, I'm not sure if you said before, but what was the problem? Does it just not work?  Furthermore, what firmware are you currently running? Could you put a blank eboot.bin (a blank file called eboot.bin) in ux0:/rePatch/PCSG00351 to see if it prevents it from running?

**Comment by the-importer** [comment]
@dots-tb 
Yes, PCSG00351 is Phantasy Star Nova and my issue is that the English translation doesn't work when I try to use the CPK translation file with rePatch and the physical card. As for your test, I try it today and let you know.

**Comment by dots-tb** [comment]
What firmware?

**Comment by the-importer** [comment]
@dots-tb 
3.68

**Comment by dots-tb** [comment]
#7 I suspect its 3.68. But report back to this thread with the replacement results.
